### ISSUE TITLE
Actual Full body tracking / Hip tracker support

### ISSUE THREAD

**Issue by manyesatge** [TheNexusAvenger/Enigma#13] opened 2024-09-29 21:53 UTC
I don't know if this is going to happen or is being worked on but we need:

Hip tracking support so that its actually full body tracking

**Comment by TheNexusAvenger** [comment] 2024-09-29 23:32
Duplicate of https://github.com/TheNexusAvenger/Enigma/issues/12

**Closed by TheNexusAvenger** 2024-09-29 23:32 UTC
Labels: bug
